---
- name: Load database specific default variables
  include_vars:
    file: "{{ lookup('first_found', params) }}"
    name: default_database_vars
  vars:
    params:
      files:
        - '{{ database_variant }}.yml'
      paths:
        - 'vars'

- name: Set database specific variables
  ansible.builtin.set_fact:
    db_dump_options: "{{ db_dump_options | default(default_database_vars.db_dump_options) }}"
    db_dump_filename: "{{ db_dump_filename | default(default_database_vars.db_dump_filename) }}"
    db_user: "{{ db_user | default(default_database_vars.db_user) }}"
    db_name: "{{ db_name | default(default_database_vars.db_name) }}"

- name: Set database dump command
  ansible.builtin.set_fact:
    db_dump_command: "pg_dump {{ db_dump_options }} -U {{ db_user }} {{ db_name }}"
  when: database_variant == 'postgres'

- name: Export database
  ansible.builtin.shell:
    chdir: '{{ docker_directory_path }}'
    cmd: "{{ docker_command }} exec {{ db_service }} bash -c '{{ db_dump_command }}' > {{ db_dump_filename }}"

- name: Download database
  ansible.builtin.fetch:
    flat: true
    src: "{{ [docker_directory_path, db_dump_filename ] | path_join }}"
    dest: "{{ [playbook_dir, 'data'] | path_join }}/"
